/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.assignment_3;

import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tetar_
 */
public class Panel extends javax.swing.JFrame {
    
    

    /**
     * Creates new form Panel
     */
    public Panel() throws IOException {

        initComponents();
    }
    
    //TASK1'de combobox'a user_idları eklenmekte
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        target_user_box = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        x_value = new javax.swing.JTextField();
        k_value = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        advice_list1 = new javax.swing.JTextArea();
        get_recommend_bt = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        movie_combo1 = new javax.swing.JComboBox<>();
        movie_combo2 = new javax.swing.JComboBox<>();
        movie_combo3 = new javax.swing.JComboBox<>();
        movie_combo4 = new javax.swing.JComboBox<>();
        movie_combo5 = new javax.swing.JComboBox<>();
        movie_vote1 = new javax.swing.JTextField();
        movie_vote2 = new javax.swing.JTextField();
        movie_vote3 = new javax.swing.JTextField();
        movie_vote4 = new javax.swing.JTextField();
        movie_vote5 = new javax.swing.JTextField();
        get_recommend_bt2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        advice_list2 = new javax.swing.JTextArea();
        x_value2 = new javax.swing.JTextField();
        k_value2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jPanel1);

        target_user_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "601", "602", "603", "604", "605", "606", "607", "608", "609", "610", " " }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("X:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("K:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Target User:");

        k_value.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                k_valueActionPerformed(evt);
            }
        });

        advice_list1.setColumns(20);
        advice_list1.setRows(5);
        jScrollPane1.setViewportView(advice_list1);

        get_recommend_bt.setText("Get Recommendations");
        get_recommend_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_recommend_btActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Recommendations");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(target_user_box, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(x_value, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(k_value, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addComponent(get_recommend_bt)
                        .addGap(89, 89, 89))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(target_user_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1)
                    .addComponent(x_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(k_value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(get_recommend_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Task1", jPanel3);

        movie_combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Assassins(1995)", "Balto(1995)", "D.A.R.Y.L.(1985)", "GoldenEye(1995)", "Copycat(1995)", "Powder(1995)", "IAmDavid(2003)", "Birth(2004)", "Ray(2004)", "Saw(2004)" }));

        movie_combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Assassins(1995)", "Balto(1995)", "D.A.R.Y.L.(1985)", "GoldenEye(1995)", "Copycat(1995)", "Powder(1995)", "IAmDavid(2003)", "Birth(2004)", "Ray(2004)", "Saw(2004)" }));

        movie_combo3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Assassins(1995)", "Balto(1995)", "D.A.R.Y.L.(1985)", "GoldenEye(1995)", "Copycat(1995)", "Powder(1995)", "IAmDavid(2003)", "Birth(2004)", "Ray(2004)", "Saw(2004)" }));

        movie_combo4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Assassins(1995)", "Balto(1995)", "D.A.R.Y.L.(1985)", "GoldenEye(1995)", "Copycat(1995)", "Powder(1995)", "IAmDavid(2003)", "Birth(2004)", "Ray(2004)", "Saw(2004)" }));

        movie_combo5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Assassins(1995)", "Balto(1995)", "D.A.R.Y.L.(1985)", "GoldenEye(1995)", "Copycat(1995)", "Powder(1995)", "IAmDavid(2003)", "Birth(2004)", "Ray(2004)", "Saw(2004)" }));

        movie_vote1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movie_vote1ActionPerformed(evt);
            }
        });

        movie_vote2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movie_vote2ActionPerformed(evt);
            }
        });

        movie_vote3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movie_vote3ActionPerformed(evt);
            }
        });

        movie_vote4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movie_vote4ActionPerformed(evt);
            }
        });

        movie_vote5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                movie_vote5ActionPerformed(evt);
            }
        });

        get_recommend_bt2.setText("Get Recommendations");
        get_recommend_bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                get_recommend_bt2ActionPerformed(evt);
            }
        });

        advice_list2.setColumns(20);
        advice_list2.setRows(5);
        jScrollPane2.setViewportView(advice_list2);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("X:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("K:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Recommendations");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(movie_combo1, 0, 114, Short.MAX_VALUE)
                                    .addComponent(movie_combo3, 0, 1, Short.MAX_VALUE)
                                    .addComponent(movie_combo2, 0, 0, Short.MAX_VALUE)
                                    .addComponent(movie_combo4, 0, 1, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(movie_vote2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movie_vote1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movie_vote3, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(movie_vote4, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(movie_combo5, 0, 1, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(movie_vote5, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(57, 57, 57))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(x_value2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(k_value2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(get_recommend_bt2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(78, 78, 78))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(movie_combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(movie_vote1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(16, 16, 16)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(movie_combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movie_vote2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(movie_combo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movie_vote3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(movie_combo4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movie_vote4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(movie_combo5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(movie_vote5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(x_value2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(k_value2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59)
                        .addComponent(get_recommend_bt2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Task2", jPanel4);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void k_valueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_k_valueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_k_valueActionPerformed

    
    //Kullanıcının verdiği en yüksek oyu döndüren ve bu oyu arrayden silmektedir.
    public int get_max_index_and_delete(double[] arr) {

        int maxIndex = 0;
        double maxValue = arr[0];

        for (int i = 1; i < arr.length; i++) {
            if (arr[i] > maxValue) {
                maxValue = arr[i];
                maxIndex = i;
                arr[i] = 0.0;
            }
        }

        return maxIndex;

    }

    //Combobox'da seçilen kullanıcının beğendiği filmlere en yakın X adet kullanıcı için K adet film önermektedir.
    private void get_recommend_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_recommend_btActionPerformed
        
                            read_csv read = new read_csv();

        advice_list1.setText("");
        MaxHeap maxHeap = new MaxHeap(600);
        
        int index = target_user_box.getSelectedIndex();
        double[] target_votes;

        double[][] main_votes;

        User[] users = new User[600];

        try {
            target_votes = read.target_user_votes(index);
            main_votes = read.main_data_votes();

            int user_index = 0;
            
            //combobox'da seçilen kullanıcının oylarının bulunduğu array ile 
            //tüm main_data'da bulunan tüm kullanıcıların oy arrayi karşılaştırılacak.
            //Cosine similarity fonksiyonu ile benzerlik hesaplanacak ve heap'e bu değer eklenecek.
            for (double[] main_vote : main_votes) {

                double rate = Cosine_similarity.cosine_similarity(target_votes, main_vote);
                //Her karşılaştırılan kullanıcı User classına ait arrayde tutulur.
                users[user_index] = new User(user_index, main_vote, rate);
                maxHeap.insert(rate);
                user_index++;
            }

        } catch (IOException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //X kez heap'in ilk elemanı silinerek her seferinde
        //en yüksek benzerlik oranına saihp array elde ediliyor.
        for (int i = 0; i < Integer.parseInt(x_value.getText()); i++) {
            
            double root = (double) maxHeap.extractMax();
            for (int j = 0; j < Integer.parseInt(k_value.getText()); j++) {
                
                //en yüksek similariy değeri hangi kullanıcıya aitse o kullanıcı bulunur 
                for (User user : users) {

                    if (user.similarity_rate == root) {
                        //en yüksek filmler puanı K kez yazdırılır.
                        int film_index = get_max_index_and_delete(user.votes);

                        String[] movies = read.get_all_movies();
                        advice_list1.append(movies[film_index] + "\n");
                    }

                }

            }

        }
    maxHeap.print();
        
    }//GEN-LAST:event_get_recommend_btActionPerformed

    private void movie_vote1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movie_vote1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movie_vote1ActionPerformed

    private void movie_vote2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movie_vote2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movie_vote2ActionPerformed

    private void movie_vote3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movie_vote3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movie_vote3ActionPerformed

    private void movie_vote4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movie_vote4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movie_vote4ActionPerformed

    private void movie_vote5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_movie_vote5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_movie_vote5ActionPerformed

    private void get_recommend_bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_get_recommend_bt2ActionPerformed
        // TODO add your handling code here:
                            read_csv read = new read_csv();

        advice_list2.setText("");

        double[][] main_votes;

        User[] users = new User[600];

        int movie_id_1 = read.get_movie_id(movie_combo2.getSelectedItem().toString());
        int movie_id_2 = read.get_movie_id(movie_combo2.getSelectedItem().toString());
        int movie_id_3 = read.get_movie_id(movie_combo3.getSelectedItem().toString());
        int movie_id_4 = read.get_movie_id(movie_combo4.getSelectedItem().toString());
        int movie_id_5 = read.get_movie_id(movie_combo5.getSelectedItem().toString());

        double[] new_votes = new double[9017];
        //Arrays.fill(new_votes, 0.0);
        for (int i = 0; i < new_votes.length; i++) {
            if (movie_id_1 == i) {
                if (!"".equals(movie_vote1.getText())) {
                    new_votes[i] = Double.parseDouble(movie_vote1.getText());

                }
            } else if (movie_id_2 == i) {
                if (!"".equals(movie_vote2.getText())) {
                    new_votes[i] = Double.parseDouble(movie_vote2.getText());

                }

            } else if (movie_id_3 == i) {
                if (!"".equals(movie_vote3.getText())) {
                    new_votes[i] = Double.parseDouble(movie_vote3.getText());

                }

            } else if (movie_id_4 == i) {
                if (!"".equals(movie_vote4.getText())) {
                    new_votes[i] = Double.parseDouble(movie_vote4.getText());

                }

            } else if (movie_id_5 == i) {
                if (!"".equals(movie_vote5.getText())) {
                    new_votes[i] = Double.parseDouble(movie_vote5.getText());

                }

            }
        }
                MaxHeap maxHeap = new MaxHeap(600);

        try {
            main_votes = read.main_data_votes();

            int user_index = 0;
            for (double[] main_vote : main_votes) {

                double rate = Cosine_similarity.cosine_similarity(new_votes, main_vote);
                users[user_index] = new User(user_index, main_vote, rate);
                maxHeap.insert(rate);
                user_index++;
            }

            //Her heap node'un index değeri olmalı bu index değeri ile main_votes arrayi bulunacak
        } catch (IOException ex) {
            Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        for (int i = 0; i < Integer.parseInt(x_value2.getText()); i++) {
            double root = (double) maxHeap.extractMax();
            for (int j = 0; j < Integer.parseInt(k_value2.getText()); j++) {
                
                for (User user : users) {

                    if (user.similarity_rate == root) {
                        int film_index = get_max_index_and_delete(user.votes);

                        String[] movies = read.get_all_movies();
                        advice_list2.append(movies[film_index] + "\n");
                    }

                }

            }

        }
        
        
     
        


    }//GEN-LAST:event_get_recommend_bt2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Panel().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Panel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea advice_list1;
    private javax.swing.JTextArea advice_list2;
    private javax.swing.JButton get_recommend_bt;
    private javax.swing.JButton get_recommend_bt2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField k_value;
    private javax.swing.JTextField k_value2;
    private javax.swing.JComboBox<String> movie_combo1;
    private javax.swing.JComboBox<String> movie_combo2;
    private javax.swing.JComboBox<String> movie_combo3;
    private javax.swing.JComboBox<String> movie_combo4;
    private javax.swing.JComboBox<String> movie_combo5;
    private javax.swing.JTextField movie_vote1;
    private javax.swing.JTextField movie_vote2;
    private javax.swing.JTextField movie_vote3;
    private javax.swing.JTextField movie_vote4;
    private javax.swing.JTextField movie_vote5;
    private javax.swing.JComboBox<String> target_user_box;
    private javax.swing.JTextField x_value;
    private javax.swing.JTextField x_value2;
    // End of variables declaration//GEN-END:variables
}
